# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the SPI MCU Joypad driver
#

obj-$(CONFIG_JOYSTICK_SPI_MCU_JOYPAD)	+= spi-mcu-joypad.o
spi-mcu-joypad-y			:= spi-mcu-joypad-core.o spi-mcu-joypad-input.o spi-mcu-joypad-leds.o
